CREATE DATABASE IF NOT EXISTS task_share;

CREATE TABLE IF NOT EXISTS tasks (
    task_id  INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    status TINYINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS task_details (
    task_detail_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    status TINYINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    task_id INT,
    FOREIGN KEY(task_id)
     REFERENCES tasks (task_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);